# This compose file is meant for local development only.

version: "3"

services:

  manga-reader:
    image: library/node:14-alpine
    container_name: manga-reader
    stdin_open: true
    volumes:
      - ./manga-reader:/manga-reader
    working_dir: /manga-reader
    command: npm start
    ports:
      - 3000:3000

  manga-parser:
    image: library/node:14-alpine
    container_name: manga-parser
    volumes:
      - ./manga-parser:/manga-parser
    working_dir: /manga-parser
    command: npm run start
    ports:
    - 3001:3001